import fs from "fs/promises";
import path from "path";
import { BaseGenerator } from "./base.js";

export class TypesGenerator extends BaseGenerator {
  async generate(): Promise<void> {
    const content = this.generateContent();
    const outputPath = path.join(this.context.config.outputDir, "types.ts");

    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    await fs.writeFile(outputPath, content, "utf-8");
  }

  private generateContent(): string {
    const outputPath = path.join(this.context.config.outputDir, "types.ts");
    const endpointsPath = path.join(this.context.config.endpointsPath);
    const relativePath = path
      .relative(path.dirname(outputPath), endpointsPath)
      .replace(/\\/g, "/");
    return `// Auto-generated type definitions
// Do not edit this file manually

import type { z } from 'zod';
import { apiConfig } from '${relativePath}';


// Re-export endpoint configuration types
export type { APIConfig, APIEndpoint, HTTPMethod } from './schema';

/**
 * Type helper to extract params schema from an endpoint
 */
export type ExtractParams<T> = T extends { params: infer P extends z.ZodType }
  ? z.infer<P>
  : never;

/**
 * Type helper to extract query schema from an endpoint
 */
export type ExtractQuery<T> = T extends { query: infer Q extends z.ZodType }
  ? z.infer<Q>
  : never;

/**
 * Type helper to extract body schema from an endpoint
 */
export type ExtractBody<T> = T extends { body: infer B extends z.ZodType }
  ? z.infer<B>
  : never;

/**
 * Type helper to extract response schema from an endpoint
 */
export type ExtractResponse<T> = T extends { response: infer R extends z.ZodType }
  ? z.infer<R>
  : never;

/**
 * Import your API config to get typed endpoints
 * 
 */
export type APIEndpoints = typeof apiConfig.endpoints;

${this.generateEndpointTypes()}
`;
  }

  private generateEndpointTypes(): string {
    const types: string[] = [];

    Object.entries(this.context.apiConfig.endpoints).forEach(
      ([name, endpoint]) => {
        const cap = this.capitalize(name);
        if (endpoint.response)
          types.push(
            `export type ${cap}Response = ${this.inferNonNull(`typeof apiConfig.endpoints.${name}.response`)};`,
          );
        if (endpoint.body)
          types.push(
            `export type ${cap}Input = ${this.inferNonNull(`typeof apiConfig.endpoints.${name}.body`)};`,
          );
        if (endpoint.query)
          types.push(
            `export type ${cap}Query = ${this.inferNonNull(`typeof apiConfig.endpoints.${name}.query`)};`,
          );
        if (endpoint.params)
          types.push(
            `export type ${cap}Params = ${this.inferNonNull(`typeof apiConfig.endpoints.${name}.params`)};`,
          );
      },
    );

    return types.join("\n");
  }
}
